# Parameter definitions
# kf = Forward reaction constant
# kr = Reverse reaction constant
# Kmr = Michelias Menton Constant of reaction
# kfd/krd = Reaction constant that brings dissociation
# ks = Rate of synthesis
# kd = Rate of degradation
# Km = MM Constant for degradation

    function params(; kwargs...)
        defaults = (
            kf_CCNDCDK4 = 10, # Forward rate constant for the reaction of CCND, CDK4 to CCND_CDK4
            kr_CCNDCDK4 = 2, # Reverse rate constant for the reaction of CCND, CDK4 to CCND_CDK4
            kf_CCNDCDK4p = 0.005, # Rate constant for forward regulator, WEE1, on the reaction of CCND_CDK4 to CCND_CDK4p
            kr_CCNDCDK4p = 1.5, # Rate constant for reverse regulator, CDC25Ap, on the reaction of CCND_CDK4 to CCND_CDK4p
            kf_RBE2F = 20.0, # Forward rate constant for the reaction of E2F, RB1 to RB_E2F
            kr_RBE2F = 0.55, # Reverse rate constant for the reaction of E2F, RB1 to RB_E2F
            kf_pRBE2F = 90.0, # Rate constant for forward regulator, CCND_CDK4, on the reaction of RB_E2F to pRB_E2F
            kr_pRBE2F = 0.01, # Reverse rate constant for the reaction of RB_E2F to pRB_E2F
            kf_E2F_ppRB = 5, # Rate constant for forward regulator, CCNE_CDK2, on the reaction of pRB_E2F to E2F,, ppRB
            kr_E2F_ppRB = 0.001, # Reverse rate constant for the reaction of pRB_E2F to E2F, ppRB
            kf_RB = 5.0, # Forward rate constant of ppRB to RB via PP1.
            kf_CCNECDK2 = 3, # Forward rate constant for the reaction of CCNE, CDK2 to CCNE_CDK2
            kr_CCNECDK2 = 0.5, # Reverse rate constant for the reaction of CCNE, CDK2 to CCNE_CDK2
            kf_CCNECDK2p = 0.2, # MM constant for enzymatic conversion of CCNE_CDK2 to CCNE_CDK2p
            kr_CCNECDK2p = 12, # MM constant for enzymatic conversion of CCNE_CDK2 to CCNE_CDK2
            kf_CDC25Ap_1 = 10, # Forward rate constant for enzymatic conversion of CDC25A to CDC25Ap via CCNA_CDK2
            kf_CDC25Ap_2 = 20, # Forward rate constant for enzymatic conversion of CDC25Ap to CDC25Ap via CCNE:CDK2
            kr_CDC25Ap = 0.3, # MM constant for enzymatic conversion of CDC25A to CDC25A
            Kmr_CDC25Ap = 0.1, # MM constant for enzymatic conversion of CDC25A to CDC25Ap
            kf_CCNACDK2 = 2, # Forward rate constant for the reaction of CCNA, CDK2 to CCNA_CDK2
            kr_CCNACDK2 = 0.5, # Reverse rate constant for the reaction of CCNA, CDK2 to CCNA_CDK2
            kf_CCNACDK2p = 0.1, # Forward rate constant for enzymatic conversion of CCNA_CDK2 to CCNA_CDK2p
            kr_CCNACDK2p = 5, # Reverse rate constant for enzymatic conversion of CCNA_CDK2 to CCNA_CDK2p
            kf_CCNBCDK1 = 6, # Forward rate constant for association of CCNB1 and CDK1
            kr_CCNBCDK1 = 0.15, # Reverse rate constant for dissociation of MPF
            kr_CCNBCDK1p_1 = 3, # Dephosphorylation rate constant of CCNB_CDK1p by CDC25CP
            kr_CCNBCDK1p_2 = 0.2, # Dephosphorylation rate constant of CCNB_CDK1p by CDC25C
            kf_CCNBCDK1p_1 = 20, # Phosphorylation rate constant of CCNB_CDK1 by WEE1
            kf_CCNBCDK1p_2 = 0.1, # Dephosphorylation rate constant of CCNB_CDK1 by WEE1P
            kf_PLK1p_1 = 0.1, # Phosphorylation rate constant of PLK1 by MPF
            kf_PLK1p_2 = 2.4, # Rate constant for forward regulator, CCNA_CDK2, on the reaction of PLK1 to PLK1p
            kr_PLK1p = 1.4, # Dephosphorylation rate constant of PLK1P
            Kmr_PLK1p = 0.1, # MM constant for enzymatic conversion of PLK1p to PLK1
            kf_WEE1p_1 = 15, # Phosphorylation rate constant of WEE1 by CCNB_CDK1
            kf_WEE1p_2 = 5.25, # Phosphorylation rate constant of WEE1 by PLK1P
            kf_WEE1p_3 = 1.5, # Phosphorylation rate constant of WEE1 by CCNA_CDK2
            kr_WEE1p = 1.5, # Dephosphorylation rate constant of WEE1 by PPase
            Kmr_WEE1p = 0.1, # MM constant for enzymatic conversion of WEE1p to WEE1
            kf_CDC25Cp_1 = 1.67, # Phosphorylation rate constant of CDC25C by MPF
            kf_CDC25Cp_2 = 2.5, # Phosphorylation rate constant of CDC25C by PLK1P
            kr_CDC25Cp = 1, # Dephosphorylation rate constant of CDC25CP by PPase
            Kmr_CDC25Cp = 0.1, # MM constant for enzymatic conversion of CDC25Cp to CDC25C
            kr_p21CCNBCDK1 = 8, # Forward rate constant for dissociation of CDKN1A:MPF
            kf_p21CCNBCDK1 = 80, # Reverse rate constant for association of CDKN1A and MPF
            kf_PPase = 5, # Dephosphorylation rate constant of PPaseP
            kr_PPase = 40, # Phosphorylation rate constant of PPase by MPF
            kf_PTTG1 = 5, # Phosphorylation rate constant of PTTG1 by MPF
            kr_PTTG1 = 0.01, # Dephosphorylation rate constant of PTTG1P by PPase
            Kmr_PTTG1 = 0.1, # MM constant for enzymatic conversion of PTTG1p to PTTG1
            kf_LMNAp = 1, # Phosphorylation rate constant of LMNA by MPF
            kr_LMNAp = 1, # Dephosphorylation rate constant of LMNAP
            kf_CDH1p_1 = 24, # Phosphorylation rate constant of CDH1 by MPF
            kf_CDH1p_2 = 24, # Phosphorylation rate constant of CDH1 by PLK1
            kf_CDH1p_3 = 20, # Phosphorylation rate constant of CDH1 by CCNE_CDK2
            kf_CDH1p_4 = 12, # Phosphorylation rate constant of CDH1 by CCNA_CDK2
            kr_CDH1p = 0.4, # Dephosphorylation rate constant of CDH1P by PPase
            Kmr_CDH1p = 0.1, # MM constant for enzymatic conversion of CDH1p to CDH1
            kf_CDC20p_1 = 5, # Phosphorylation rate constant of CDC20 by MPF
            kf_CDC20p_2 = 36, # Phosphorylation rate constant of CDC20 by PLK1p
            kr_CDC20p = 20, # Dephosphorylation rate constant of CDC20 by PPase
            Kmr_CDC20p = 0.1, # MM constant for enzymatic conversion of CDC20p to CDC20
            kf_APCCP_1 = 2, # Phosphorylation rate constant of APC/C by MPF
            kf_APCCP_2 = 2, # Phosphorylation rate constant of APC/C by PLK1p
            kr_APCCP = 0.8, # Dephosphorylation rate constant of APC/CP by PPase
            Kmr_APCCP = 0.1, # MM constant for enzymatic conversion of APCCP to APCC
            kf_APCCPCDC20 = 80, # Forward rate constant for association of APC/CP and CDC20
            kr_APCCPCDC20 = 20, # Reverse rate constant for dissociation of APC/CP:CDC20
            kfd_APCCPCDC20 = 0.04, # Dephosphorylation rate constant of APC/CP:CD20 by PPase (dissociation)
            kfd_APCCCDC20_1 = 5, # Phosphorylation rate constant of APC/C:CDC20 by MPF (dissociation)
            kfd_APCCCDC20_2 = 5, # Phosphorylation rate constant of APC/C:CDC20 by PLK1p (dissociation)
            kf_APCCCDH1p_1 = 0.1, # Phosphorylation rate constant of APC/C:CDH1 by MPF to APC/CP:CDH1 (inactive)
            kf_APCCCDH1p_2 = 0.3, # Phosphorylation rate constant of APC/C:CDH1 by PLK1p to APC/CP:CDH1 (inactive)
            kr_APCCCDH1p = 0.04, # Dephosphorylation rate constant of APC/CP:CDH1 by PPase to APC/C:CDH1 (active)
            Kmr_APCCCDH1p = 0.1, # MM constant for enzymatic conversion of APCCP_CDH1 to APCC_CDH1
            kf_APCCCDH1 = 80, # Forward rate constant for association of APC/C and CDH1
            kr_APCCCDH1 = 20, # Reverse rate constant for dissociation of APC/C:CDH1
            kf_APCCCDH1p_3 = 80, # Forward rate constant for association of APC/CP and CDH1
            kr_APCCCDH1p_3 = 3, # Reverse rate constant for dissociation of APC/CP:CDH1
            kfd_APCCCDH1_1 = 24, # Phosphorylation rate constant of (APCC)CDH1 by MPF (dissociation)
            kfd_APCCCDH1_2 = 24, # Phosphorylation rate constant of (APCC)CDH1 by PLK1p (dissociation)
            kfd_APCCPCDH1_1 = 24, # Phosphorylation rate constant of (APCCP)CDH1 by MPF (dissociation)
            kfd_APCCPCDH1_2 = 24, # Phosphorylation rate constant of (APCCP)CDH1 by PLK1p (dissociation)
            kr_EMI1p = 1, # Forward rate constant of EMI1p to EMI1
            kf_EMI1p = 40, # Reverse rate constant of EMI1 to EMI1p by PLK1p
            kf_APCCPCDC20EMI1 = 12, # Forward rate constant for the reaction of APCCP_CDC20, EMI1 to APCCP_CDC20_EMI1
            kr_APCCPCDC20EMI1 = 1, # Reverse rate constant for the reaction of APCCP_CDC20, EMI1 to APCCP_CDC20_EMI1
            kf_APCCCDH1EMI1 = 5, # Forward rate constant for the reaction of APCC_CDH1, EMI1 to APCC_CDH1_EMI1
            kr_APCCCDH1EMI1 = 1, # Reverse rate constant for the reaction of APCC_CDH1, EMI1 to APCC_CDH1_EMI1
            kf_p21CCNECDK2 = 80, # Association of p21 and CCNE:CDK2, inhibiting
            kr_p21CCNECDK2 = 8, # Dissociation of p21:CCNE:CDK2
            kf_p21CCNACDK2 = 80, # Association of p21 and CCNA:CDK2, inhibiting
            kr_p21CCNACDK2 = 8, # Dissociation of p21:CCNA:CDK2
            kf_ATMp = 0, # Phosphorylation of ATM to active form via double stranded DNA break
            kr_ATMp = 1, # Dephosphorylationof ATMp to inactive form via PP2A
            kf_CHK2p = 1, # Phosphorylation of Chk2 to active form via ATMp
            kr_CHK2p = 1, # Dephosphorylationof Chk2p to inactive form via PP2A/PP1
            kf_p53p = 1, # Phosphorylation of p53 to active form via Chk2p
            kr_p53p = 1, # Dephosphorylationof p53 to inactive form
            kf_p53MDM2 = 1, # Association of p53 with MDM2 (inhibiting)
            kr_p53MDM2 = 1, # Dissociation of p53:MDM2
            kf_GemininCDT1 = 3, # Association of Geminin and CDT1
            kr_GemininCDT1 = 0.1, # Dissociation of Geminin and CDT1

            ks_CCND = 0.05, # Synthesis rate constant of CCND
            ks_E2F = 0.06, # Synthesis rate constant of E2F
            ks_CCNE_E2F = 0.1, # Synthesis rate constant of CCNE by factor E2F
            ks_CCNE_pRBE2F = 0.1, # Synthesis rate constant of CCNE by factor pRB_E2F
            ks_CDC25A_E2F = 0.105, # Synthesis rate constant of CDC25A by factor E2F
            ks_CCNA_E2F = 0.25, # Synthesis rate constant of CCNA by factor E2F
            ks_CCNB_CCNACDK2 = 0.24, # Synthesis rate constant of CCNB by factor CCNA_CDK2
            ks_WEE1 = 0.01, # Synthesis rate constant of WEE1
            ks_CDC25C = 0.2, # Synthesis rate constant of CDC25C
            ks_PLK1 = 0.5, # Synthesis rate constant of PLK1
            ks_PTTG1 = 0.1, # Synthesis rate constant of PTTG1
            ks_CDC20 = 0.0333, # Synthesis rate constant of CDC20
            ks_CDH1 = 0.1, # Synthesis rate constant of CDH1
            ks_p21 = 1e-04, # Synthesis rate constant of p21
            ks_SCF_CCNECDK2 = 0.1, # Synthesis rate constant of SCF by factor CCNE_CDK2
            ks_EMI1_E2F = 0.05, # Synthesis rate constant of EMI1 by factor E2F
            ks_p53 = 0.01, # Basal synthesis rate of p53
            ks_MDM2_p53p = 0.1, # Synthesis of MDM2 via p53p
            ks_CDT1_E2F = 0.025, # Synthesis of CDT1 via E2F
            ks_Geminin_E2F = 0.025, # Synthesis of Geminin via E2F
            ks_RB = 0.02, # Constant synthesis of Rb

            kd_CCND_SCF = 6, # Enzymatic degradation rate constant of CCND by SCF
            kd_CCNDCDK4_SCF = 1.0, # Degradation of CCND:CDK4 and CCND:CDK4p by SCF
            kd_E2F_CDH1 = 0.002, # Degradation rate of E2F via APCCP:CDH1.
            kd_E2F_SCF = 5, # Degradation rate of E2F via SCF.
            kd_CCNE_SCF = 0.5, # Enzymatic degradation rate constant of CCNE by SCF
            kd_CCNECDK2_SCF = 1.26, # Enzymatic degradation rate constant of CCNECDK2 and CCNDCDK2p by SCF
            kd_CDC25A_CDH1 = 0.15, # Enzymatic degradation rate constant of CDC25A by APCC_CDH1
            kd_CDC25A_SCF = 2.5, # Enzymatic degradation rate constant of CDC25A by SCF
            kd_CCNA_CDC20 = 2.0, # Enzymatic degradation rate constant of CCNA by APCCP_CDC20
            kd_CCNA_CDH1 = 0.3, # Enzymatic degradation rate constant of CCNA by APCC_CDH1
            kd_CCNACDK2_CDC20 = 3.0, # Enzymatic degradation rate constant of CCNACDK2 and CCNACDK2p by APCCP_CDC20
            kd_CCNACDK2_CDH1 = 0.01, # Enzymatic degradation rate constant of CCNACDK2 and CCNACDK2p  by APCC_CDH1
            kd_CCNB_CDC20 = 1, # Enzymatic degradation rate constant of CCNB by APCCP_CDC20
            kd_CCNB_CDH1 = 1, # Enzymatic degradation rate constant of CCNB by APCC_CDH1
            kd_CCNBCDK1p_CDC20 = 1, # MM rate for degradation of CCNB_CDK1p
            kd_CCNBCDK1p_CDH1 = 1, # MM constant for degradation of CDK1
            kd_CCNBCDK1_CDC20 = 10, # MM constant for degradation of CDK1
            kd_CCNBCDK1_CDH1 = 1.1, # MM constant for degradation of CDK1
            kd_WEE1p_SCF = 0.5, # MM Degradation rate constant for WEE1p by SCF
            kd_CDC25C_CDH1 = 3.0, # Enzymatic degradation rate constant of CDC25C by APCC_CDH1
            kd_PLK1_CDH1 = 1.25, # Enzymatic degradation rate constant of PLK1 by APCC_CDH1
            kd_PTTG1_CDC20 = 10, # Enzymatic degradation rate constant of PTTG1 by APCCP_CDC20
            kd_PTTG1p_CDC20 = 10, # Enzymatic degradation rate constant of PTTG1p by APCCP_CDC20
            kd_CDC20_CDH1 = 8, # Enzymatic degradation rate constant of CDC20 by APCC_CDH1
            kd_CDH1p_SCF = 7.2, # Degradation of CDH1p by SCF
            kd_p21 = 0.1, # p21 self-degradation
            kd_p21_SCF = 1, # p21 degradation by SCF
            kd_p21_CDC20 = 1, # p21 degradation by APC:CP/CDC20
            kd_p21CCNECDK2_SCF = 0.1, # p21 degradation from p21:CCNE:CDK2 degradation by SCF
            kd_p21CCNACDK2_SCF = 0.1, # p21 degradation from p21:CCNA:CDK2 degradation by SCF
            kd_p21CCNBCDK1_SCF = 0.1, # p21 degradation from p21:CCNB:CDK1 by SCF
            kd_p21CCNECDK2_CDC20 = 0.1, # p21 degradation from p21:CCNE:CDK2 degradation by APC/CP:CDC20
            kd_p21CCNACDK2_CDC20 = 0.1, # p21 degradation from p21:CCNA:CDK2 degradation by APC/CP:CDC20
            kd_p21CCNBCDK1_CDC20 = 1, # p21 degradation  from p21:CCNB:CDK1 by APC/CP:CDC20
            kd_SCF_CDH1 = 5, # Enzymatic degradation rate constant of SCF by APCCT_CDH1
            kd_EMI1p_SCF = 1, # Enzymatic degradation rate constant of EMI1p by SCF
            kd_MDM2_ATMp = 1, # Degradation of MDM2 via ATMp pathway
            kd_p53MDM2 = 1, # Degradation of P53 bonded to MDM2, releases MDM2
            kd_CDT1_SCF = 6, # Degradation of CDT1 via SCF
            kd_Geminin_CDH1 = 3, # Degradation of Geminin via APC/C:CDH1
            kd_GemininCDT1_CDH1 = 0.5, # Degradation of Geminin from Geminin:CDT1 complex via APC/C:CDH1
            kd_RB = 0.1, # Degradation of RB
            kd_E2F = 0.1, # Degradation of E2F
            kd_RBE2F_CDH1 = 0.4, # Degradation of RBE2F by CDH1
            kd_RBE2F_SCF = 0.1, # Degradation of RBE2F by SCF
            kd_p53 = 0.1, # Degradation of p53
            
            Km_CCND_SCF = 0.1, # MM constant for degradation of CCND
            Km_CCNDCDK4_SCF = 0.1, # MM constant of CCND from CCND:CDK4 degradation by SCF
            Km_E2F_CDH1 = 0.1, # MM constant for degradation of E2F vis APCCP:CDH1.
            Km_E2F_SCF = 0.1, # MM constant for degradation of E2F vis SCF.kf_9_1
            Km_CCNE_SCF = 0.1, # MM constant for degradation of CCNE
            Km_CCNECDK2_SCF = 0.1, # MM constant for degradation of CCNE_CDK2
            Km_CDC25A_CDH1 = 0.1, # MM constant for degradation of CDC25A
            Km_CDC25A_SCF = 0.1, # MM constant for degradation of CDC25A
            Km_CCNA_CDC20 = 0.1, # MM constant for degradation of CCNA
            Km_CCNA_CDH1 = 0.1, # MM constant for degradation of CCNA by APCC_CDH1
            Km_CCNACDK2_CDC20 = 0.1, # MM constant for degradation of CCNACDK2 by APCCP_CDC20
            Km_CCNACDK2_CDH1 = 0.1, # MM constant for degradation of CCNACDK2 by APCC_CDH1
            Km_CCNB_CDC20 = 0.1, # MM constant for degradation of CCNB by APCCP_CDC20
            Km_CCNB_CDH1 = 0.1, # MM constant for degradation of CCNB by APCC_CDH1
            Km_CCNBCDK1p_CDC20 = 0.1, # MM constant for degradation of CCNB_CDK1p
            Km_CCNBCDK1p_CDH1 = 0.1, # MM constant for degradation of CCNB_CDK1p
            Km_CCNBCDK1_CDC20 = 0.1, # MM constant for degradation of CCNB_CDK1
            Km_CCNBCDK1_CDH1 = 0.1, # MM constant for degradation of CCNB_CDK1
            Km_WEE1p_SCF = 0.1, # MM constant for the degradation of WEE1p by SCF
            Km_CDC25C_CDH1 = 0.1, # MM constant for degradation of CDC25C
            Km_PLK1_CDH1 = 0.1, # MM constant for degradation of PLK1
            Km_PTTG1_CDC20 = 0.1, # MM constant for degradation of PTTG1
            Km_PTTG1p_CDC20 = 0.1, # MM constant for degradation of PTTG1p
            Km_CDC20_CDH1 = 0.1, # MM constant for degradation of CDC20
            Km_CDH1p_SCF = 0.1, # MM constant for degradation of CDH1p
            Km_SCF_CDH1 = 0.1, # MM constant for degradation of SCF
            Km_EMI1p_SCF = 0.1, # MM constant for degradation of EMI1p
            Km_CDT1_SCF = 0.1, # MM constant for degradation of CDT1
            Km_Geminin_CDH1 = 0.1, # MM constant for degradation of Geminin
            Km_GemininCDT1_CDH1 = 0.1, # MM constant for degradation of Geminin:CDT1
            Km_RBE2F_CDH1 = 0.1, # MM constant for degradation of RBE2F by CDH1
            Km_RBE2F_SCF = 0.1, # MM constant for degradation of RBE2F by SCF
            Km_MDM2_ATMp = 0.1, # MM constant for degradation of MDM2
            Km_p21_SCF = 0.1, # MM constant of p21 degradation by SCF
            Km_p21_CDC20 = 0.1, # MM constant of p21 degradation by APC/CP:CDC20
            Km_p21CCNECDK2_SCF = 0.1, # MM constant of p21 from p21:CCNE:CDK2 degradation by SCF
            Km_p21CCNACDK2_SCF = 0.1, # MM constant of p21 from p21:CCNE:CDK2 degradation by SCF
            Km_p21CCNBCDK1_SCF = 0.1, # MM constant of p21 from p21:CCNA:CDK2 degradation by SCF
            Km_p21CCNECDK2_CDC20 = 0.1, # MM constant of p21 from p21:CCNE:CDK2 degradation by APC/CP:CDC20
            Km_p21CCNACDK2_CDC20 = 0.1, # MM constant of p21 from p21:CCNA:CDK2 degradation by APC/CP:CDC20
            Km_p21CCNBCDK1_CDC20 = 0.1, # MM constant of p21:CCNB:CDK1 degradation by APC/CP:CDC20
            ki_PLK1 = 2, # Inhibition constant of PLK1
            α = 2.3, # Time Scale constant
            con_VOL = 0, # Concentration of volasertib (nM)
            EC50_VOL = 2.33, #Half-maximal effective concentration (nM)
            n_VOL = 8.14, # Hill constant for volasertib inhibition equation of PLK1
            con_ABE = 0, # Concentration of volasertib (μM)
            EC50_ABE = 0.129, #Half-maximal effective concentration (μM)
            n_ABE = 1.91, # Hill constant for Abemaciclib inhibition equation of CCND:CDK4
        )
        user_params = merge(defaults, kwargs)
        return ComponentVector{Float64}(user_params)
    end
    
    
    